### ISSUE TITLE
The channel-like reads can behave like await

### ISSUE THREAD

**Issue by fhackett** [UBC-NSS/pgo#105]
With the introduction of channel-like mapping macros, variable reads can now fail. That is, we are able to add await-like semantics to read.

This has a particular effect on the aborting semantics of either branches - now not only can you abort an either branch by typing `await`, you can also do this by reading a variable. Our `ArchetypeResource` interface does not support this result of a read operation - we would need to add at least a second return value to the read operation indicating that the read has failed (kind of like would-block semantics in POSIX socket programming). We also need to ensure that channel-like reads revert properly under abort conditions: since reading can pop a value off a queue (that is, mutate the context in some way), we need to ensure that this operation is undone on aborts.

Current status: fix later, we will not support this until we get our MVP working. Reads outside of either statements will block, and (archetype parameter) reads inside either statements will fail at compile time. We should however take care to avoid design decisions that will make the above modifications unreasonably hard.

**Comment by rmascarenhas** [comment]
Closing since this is an old discussion.
