### ISSUE TITLE
Double Unlock Error

### ISSUE THREAD

**Issue by rmascarenhas** [UBC-NSS/pgo#118]
```
      mainLoop:
        while (TRUE) {
          leaderLoop:
             while (~electionInProgress[self] /\ iAmTheLeader[self]) {
                 index := 3*NUM_NODES;

                 heartbeatBroadcast:
                   BroadcastHeartbeats(mailboxes, [type |-> HEARTBEAT_MSG, leader |-> self - 3*NUM_NODES], index, self);

                 sleeper := heartbeatFrequency;
             };

          followerLoop:
            while (~electionInProgress[self] /\ ~iAmTheLeader[self]) {
                msg := mailboxes[self];
                assert(msg.type = HEARTBEAT_MSG);
                lastSeen := msg;
            };
     }
```

In the above specification, the transition between `leaderLoop` and `followerLoop` is currently not computed correctly. We generate code that terminates the critical section when the `leaderLoop` is false; and then again when starting `followerLoop` (leading to a double-free error).

We temporarily disabled double-free checking in the runtime:

https://github.com/UBC-NSS/pgo/blob/30aa92f82d6088a609c4ec4b3137555d6c909e5f/src/runtime/pgo/distsys/archetypes.go#L124-L126

 This should, however, be enabled again when the issue above is fixed.

**Comment by bestchai** [comment]
Can you add file name and line number where double locking is disable, so that the bug can be easily reproduced?

**Comment by rmascarenhas** [comment]
Updated original description.
