### ISSUE TITLE
 Implement thread safe reading of variables 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#13]
Currently, PGoTransStageAtomicity only considers variables that are assigned to when determining locking, and it does not consider that variables that are accessed in the step also need thread-safe access. We should walk all TLA expressions seen in the step, which will contain all variables that are accessed. With the accessed variables, we should `RLock` the corresponding mutexes.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/41/implement-thread-safe-reading-of-variables

**Comment by fhackett** [comment]
@mrordinaire did your rework of atomicity/state fix this?

**Comment by mrordinaire** [comment]
it fixed the issue of protecting variables that are read. It does not yet distinguish between reads and writes, i.e. all locks are exclusive locks and there's no support for read locks.
