### ISSUE TITLE
Distributed Objects and better global state API

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#16]
### Goals
* To distribute state across processes; different processes would be responsible for part of the global state; processes would then make RPC calls to an object "owner" to get access to it;
* First implementation is going to be naive (based on lock groups); lots of opportunities for optimization here, by finding optimal object placement (depending on how often processes access global state, detection of communication channels, etc.)
* This would include a better, location-independent API that allows processes to access global state. Instead of having `globalState.GetStringCollection()`, we could have `queue.Get()`, where `queue` is a struct defined in the `pgonet` package that handles `Get` according to the variable type. All types implement the same interface. Also, `Get` could be translated to a local data-structure access or an RPC call to the processes that "owns" the object.

**Comment by rmascarenhas** [comment]
I made some updates to the original description of this issue. Namely, I'm including the results of our recent discussions about global state management in this task. The first implementation (which I'm working on right now) will be simple and limited to using existing lock grouping functionality. I also plan to improve the API exposed by the `pgonet` to provide an API based on the idea of "location-independent objects."

Let me know if you have comments about this.

**Comment by rmascarenhas** [comment]
Closing this since the existing runtime API in the `state-server` strategy was chosen.
