### ISSUE TITLE
Implement missing/incomplete visit methods in convertStatementToGo

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#2]
Several methods that visit different PlusCal AST types have not been implemented (e.g. those for await, when) and some need to have additional functionality implemented (e.g. return). Implementing these involves first determining an equivalent Go expression to compile to.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/4/implement-missing-incomplete-visit-methods

**Comment by rmascarenhas** [comment]
Outdated.
