### ISSUE TITLE
Panicking when trying to write to a local array

### ISSUE THREAD

**Issue by shayanh** [UBC-NSS/pgo#202]
Local variables are compiled as `LocalArchetypeResource`s. When you have a local variable that is an array, you can update it like this:
```
log[1] := 3;
```

The compiled Go output, uses `Index()` method on the `log` resource, which is  `LocalArchetypeResource`. This causes the following panic:
```
internal error: attempted to index a leaf archetype resource
```

I have attached a simple program to demonstrate this bug.

[index.zip](https://github.com/UBC-NSS/pgo/files/7604985/index.zip)

**Comment by fhackett** [comment]
That's a really important bug!

I totally forgot to consider that "special" feature of local vars...
I've been working on it for a little bit, so fix coming in just a moment.
