### ISSUE TITLE
 Add more TLA+ operators if necessary 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#3]
PlusCal may support some TLA+ operations that may not be found in the TLAExprParser token dictionary. If these exist, we need to add them to the dictionary and handle them properly.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/11/add-more-tla-operators-if-necessary

**Comment by mrordinaire** [comment]
The most important operators that are not parsed (properly) are the Cartesian product operator `\X`, the `IF...THEN...ELSE` expression and `CASE` construct, and the `DOMAIN` operator. It is also possible to use multiple `|->` operators in one map declaration, like in `["a" |-> 1, "b" |-> 2, "c" |-> 3]`.

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/11/add-more-tla-operators-if-necessary#comment-39332715

**Comment by rmascarenhas** [comment]
Closing this since the classes mentioned no longer exist (and we now support `IF` and `CASE` expressions).
