### ISSUE TITLE
 Compile a variety of non-parallel PlusCal 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#4]
We want to be able to compile a variety of single threaded PlusCal algorithms before moving on to dealing with concurrency. This should involve handling set construction, complicated variable initializations, operations, handing procedures, function calls with returns, macros, complicated loops, with statements, either statements for single threaded context. Once those tasks are done, mark this as complete. This is like a master task. Unfortunately I can't seem to find any support for master tasks that depends on sub tasks on bitbucket?

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/20/compile-a-variety-of-non-parallel-pluscal

**Comment by rmascarenhas** [comment]
No concrete goal here and we probably support most of what this mentions. Closing.
