### ISSUE TITLE
End-to-end tests

### ISSUE THREAD

**Issue by rmascarenhas** [UBC-NSS/pgo#46]
We need a better way to check that the compiled Go source does what it's supposed to do. Ideally, we would actually run the Go source files and compare their standard output against some predefined expected output.

**Comment by fhackett** [comment]
This is largely implemented as of e2a09aec8ae706313ddc28607b6779f1d121f51e. That is, we have the tests in the source tree and they work.

Bump for Travis CI (or equivalent) in order to make sure broken builds don't get pushed.

**Comment by rmascarenhas** [comment]
This is done. Specs under `test/integration` are compiled to Go, then compiled to binary, executed and their output is compared to an expected value.
