### ISSUE TITLE
 Support use of tuples with such that operator 

### ISSUE THREAD

**Issue by minhnhdo** [UBC-NSS/pgo#5]
The following TLA+ syntax is valid:

``` PlusCal
{ << x, y >> \in S \X T : P(x, y) }
```

Currently we assume that the left-hand side of the `\in` is just a single variable. We need some way to handle this case.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/28/support-use-of-tuples-with-such-that

**Comment by fhackett** [comment]
Much work has been done of this. We need to ensure `\X` works.
