### ISSUE TITLE
 Handle short form set declarations 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#6]
TLA+ supports the following declarations when declaring sets or using predicate operations:

- `\E x, y \in S : P(x, y)`,
- `\E x \in S, y \in S : P(x, y)`,
- `\E x \in S : (\E y \in S : P(x, y))`,

which are all equivalent. Only the last two operations are currently supported. We should support the first operation.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/30/handle-short-form-set-declarations

**Comment by rmascarenhas** [comment]
Currently supported.
