### ISSUE TITLE
In PGo's scoping pass, the binary minus operator is being referenced as the unary negation operator 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#70]
The TLA+ expression below is being compiled wrongly.
``` tla+
0..a-1
```
It is compiled to the following Go code.
``` go
    tmpRange := make([]int, -a - 0 + 1)
    for i := 0; i <= -a; i++ {
        tmpRange[i - 0] = i
    }
```

I've added two tests for this issue (see f8f1c53). Lexing is working correctly but the generated code is still wrong. Through some debugging, I found that the minus operator, in this case, wrongly references the negation operator. Perhaps adding the number of expected arguments to QualifiedName will fix the issue.

**Comment by fhackett** [comment]
Oh interesting, thanks for catching that. I'll try some experiments on TLC tomorrow, as in general TLC does not support overloading the same operator name (if I recall correctly). I guess they special-cased unary `-`.

I'll fix that tomorrow once I'm back from this trip.
