### ISSUE TITLE
Do not define unused variables

### ISSUE THREAD

**Issue by rmascarenhas** [UBC-NSS/pgo#87]
### Premises

* TLA+ and PlusCal do not care about declared but unused variables
* We currently define every variable declared in PlusCal
* Go does not compile code that contains unused variables
* We do not want to generate Go code that does not compile

### Conclusion

* We can generate code that does not compile if the spec declares a variable that is never used.

### Solution

* Either fail PGo compilation if a variable is declared but not used; or, preferably, omit its definition in the compiled Go program.

**Comment by mrordinaire** [comment]
I prefer ignoring unused variables and giving a warning for each of them.
