### ISSUE TITLE
 Parse indentation in TLA+ lists of boolean expressions 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#9]
TLA+ features lists of boolean operators which are alignment-sensitive. The alignment determines the precedence of the operators. In parsing TLA+ definitions into annotations, we ignore spacing. Before we tokenize the TLA+ expression, we should insert parentheses to preserve the precedence specified by the list.

A description of the alignment system is at https://link.springer.com/content/pdf/10.1007%2FBF01211870.pdf.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/34/parse-indentation-in-tla-lists-of-boolean

**Comment by mrordinaire** [comment]
The TLAToken class includes a Region which also contains indentation information, so we can put precedence parsing into the TLAExprParser class.

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/34/parse-indentation-in-tla-lists-of-boolean#comment-39226784

**Comment by fhackett** [comment]
This has been fixed as long as the new TLA+ parser has been merged (definitely as of e2a09aec8ae706313ddc28607b6779f1d121f51e)
