### ISSUE TITLE
[proposal] MPCal archetype paremeters in Go

### ISSUE THREAD

**Issue by fhackett** [UBC-NSS/pgo#95]
This is an issue documenting my ideas regarding translating MPCal archetype parameters into Go.

The general principle I've been operating under is that a parameter would be an instance of an interface like this:
```golang

type Access int

const (
    R Access = 1 // 01b
    W Access = 2 // 10b
    // RW = R|W = 11b is implied
)

type ArchVariableT interface {
    // called at the beginning of any critical section that needs the variable
    // returns the value of the variable in all cases except
    // access == W, nil in that case
    Acquire(access : Access) T
    // writes the value to the variable and ends the critical section,
    // panics if !(access & W)
    Commit(value : T)
    // ends the critical section with the value of the variable unchanged
    Abort()
}

```

Obviously T is not a real type and Go's lack of generics will as usual cause pain for code generators... but hopefully this gets the point across.

Here is an example of an archetype and its compilation (sorry if I got a compilation detail meaningfully wrong):

```
archetype ArchFoo(ref a, ref b) {
    section1:
    a := 1;
    section2:
    b := a || a := b;
    section3:
    either { a := 2; await b = 2; } or { skip };
}
```

```golang
func ArchFoo(a, b : ArchVariableInt) {
    // section1
    a.Acquire(W)
    a.Commit(1)
    // section2
    aVal, bVal := a.Acquire(R|W), b.Acquire(R|W)
    bVal, aVal := aVal, bVal
    a.Commit(aVal)
    b.Commit(bVal)
    // section3
    for {
        // option1:
        a.Acquire(W)
        bVal = b.Acquire(R)
        aVal = 2
        if bVal != 2 {
            a.Abort()
            b.Abort()
            goto option2
        }
        a.Commit(aVal)
        b.Abort() // not really an abort, but it just has
            // to "end the critical section with no write" so it's ok
        break
        option2:
        break // skip
    }
}
```

**Comment by fhackett** [comment]
@rmascarenhas thanks for your questions - I see I forgot to explain the relationship I see between our ideas.

Here is an adapter between your channel semantics and the API I described:
```golang

type ChannelVar Channel

func (self *Channel) Acquire(access Access) T {
    return self.Read()
}

func (self *Channel) Commit(T value) {
    self.Write(value)
}

func (self *Channel) Abort() { }

```

This will of course only be a correct implementation of my API if the MPCal algorithm uses the variable as if it were a channel, but that's the point. If we know that variable is a channel then the above implementation (give or take some details like whether it should latch the last value received) is perfectly adequate and most of the concurrency control semantics are redundant in this case.

If however you had a variable that did not match those semantics then you could instead provide another implementation with stronger guarantees (and worse performance), like something backed by our existing value store.

Hopefully this explains things better - let me know if I forgot something else / you find any flaws in my idea(s).

**Comment by rmascarenhas** [comment]
I see, that does make sense, @fhackett! Thanks for making it clear. I think the `Var` interface you proposed can be implemented on top of the existing distributed state API (just being thin wrappers to the existing calls).

But other than that, I guess we are on the same page :+1:

**Comment by rmascarenhas** [comment]
The runtime part of this is mostly implemented, so I'm closing this issue.
